### ISSUE TITLE
Helper methods not available

### ISSUE THREAD

**Issue by mrodriguez90** [escpos/escpos#7] opened 2019-12-22 15:55 UTC
Hi,

First of all thank you for your work.
I have a problem with helpers, if I try to use them I always get for instance "NoMethodError (undefined method `center'").

this is my report class:
---------------------------------------------------------------------------------------------------------
```ruby
class MerchantInfo < Escpos::Report

  def cfe_data
    options[:cfe_data]
  end

  def merchant_title text
    center "#{text}"
  end

  def self.create_merchant_info
    layout_dir = Rails.root.join('app/views/api/v1/thermal_cfe/merchant_info.erb').to_s
    cfe_layout = MerchantInfo.new(layout_dir,
                                  {
                                      cfe_data:Hash(merchant:COMMERCES[0])
                                  }
    )
    puts "cfe_layout #{cfe_layout.to_json}"
    cfe_layout
  end
end
```
----------------------------------------------------------------------------------------------------------
this is my view file:
#merchant_info.erb
```erb
<%=merchant_title cfe_data[:merchant]%>
```
----------------------------------------------------------------------------------------------------------
ruby version 2.5.3
rails version 5.2.1

Thank you in advance for your help.

**Comment by svoboda-jan** [comment] 2021-06-07 17:27
I edited your comment to be more readable (https://guides.github.com/features/mastering-markdown/). The example you provided should work, since by inheriting from `Escpos::Report` makes the `center` helper available.

Closing for now. If this is still an issue, please feel free to reopen and provide an working minimal example to reproduce the issue.

**Closed as completed by svoboda-jan** 2021-06-07 17:27 UTC

**Comment by trombik** [comment] 2022-01-15 13:06
> The example you provided should work

actually, it does not. the real issue is here:

https://github.com/escpos/escpos-image/issues/8
